// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  DapperDoe.Models.SnippetPreview = (function(_super) {
    __extends(SnippetPreview, _super);

    function SnippetPreview() {
      return SnippetPreview.__super__.constructor.apply(this, arguments);
    }

    return SnippetPreview;

  })(Backbone.Model);

  DapperDoe.Collections.SnippetsPreviews = (function(_super) {
    __extends(SnippetsPreviews, _super);

    function SnippetsPreviews() {
      return SnippetsPreviews.__super__.constructor.apply(this, arguments);
    }

    SnippetsPreviews.prototype.model = DapperDoe.Models.SnippetPreview;

    return SnippetsPreviews;

  })(Backbone.Collection);

  DapperDoe.Models.Snippet = (function(_super) {
    __extends(Snippet, _super);

    function Snippet() {
      return Snippet.__super__.constructor.apply(this, arguments);
    }

    return Snippet;

  })(Backbone.Model);

  DapperDoe.Collections.Snippets = (function(_super) {
    __extends(Snippets, _super);

    function Snippets() {
      return Snippets.__super__.constructor.apply(this, arguments);
    }

    Snippets.prototype.model = DapperDoe.Models.Snippet;

    return Snippets;

  })(Backbone.Collection);

}).call(this);
