// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  DapperDoe.Models.Template = (function(_super) {
    __extends(Template, _super);

    function Template() {
      return Template.__super__.constructor.apply(this, arguments);
    }

    Template.prototype.initialize = function(options) {
      return this.parseSnippets(options.callback);
    };

    Template.prototype.parseSnippets = function(callback) {
      var $snippets;
      $snippets = $('<div id="dd_snippets_loader"></div>');
      return $snippets.load("" + this.attributes.name + "/snippets.html", (function(_this) {
        return function() {
          var snippetsPreviews;
          snippetsPreviews = new DapperDoe.Collections.SnippetsPreviews();
          $snippets.children().each(function() {
            return snippetsPreviews.add({
              previewUrl: $(this).data('preview'),
              type: $(this).data('type'),
              html: $(this).html(),
              collection: snippetsPreviews
            });
          });
          _this.snippetsPreviews = snippetsPreviews;
          return callback();
        };
      })(this));
    };

    return Template;

  })(Backbone.Model);

}).call(this);
